schema:
  - https://gods-dog.flywheelsites.com/graphql
generates:
  ./graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withRefetchFn: true
